### ISSUE TITLE
通知：请译者们重置自己的代码库

### ISSUE THREAD

**Issue by OlingCat** [Go-zh/go-zh.github.io.old#25]
由于我们设置 Gerrit 时的操作失误，master 分支不小心被强制更新了，请译者们重置自己的本地代码库和Github上的 fork，方法如下：

```
git fetch upstream  # 这里是你 add remote 时设置的别名，下同。
git reset --hard upstream/master
git push -f
```

对于给您带来的麻烦，我们表示诚挚的歉意。

此外，近期代码审校工具将迁移至 Gerrit，这里将暂停接受 PR，敬请各位留意。
@Bluek404 @zieckey

**Comment by zieckey** [comment]
OK

**Comment by zieckey** [comment]
本地操作时，应该在哪个分支下工作？
zh-master还是master？

**Comment by minux** [comment]
这个代码库没有 zh-master 分支，所以就是 master 分支下进行那个操作。
（只有 go-zh.github.io受影响了）。

**Comment by zieckey** [comment]
好的

**Comment by OlingCat** [comment]
@Bluek404  @zieckey 你们现在的本地代码库里有还没 push 的提交么？

**Comment by Bluek404** [comment]
@OlingCat 无

**Comment by zieckey** [comment]
没有

**Comment by OlingCat** [comment]
啊，这样就好办了，明天我会写个转换指南，为你们本地的 repo 添加新的支持 Gerrit 的设置。

**Comment by zieckey** [comment]
好的
